/**
 * @file        lib/events/idempotency.ts
 * @purpose     Shared IdempotencyGuard class for EventBus listeners.
 *
 * ── Background ────────────────────────────────────────────────────────────────
 *   The IdempotencyGuard was previously duplicated in activity.ts and
 *   notifications-bus.ts with identical implementations.  Extracted here
 *   (Stabilization) to eliminate duplication and centralise the TTL constant.
 *
 * ── Usage ─────────────────────────────────────────────────────────────────────
 *   Each listener FILE should create its OWN IdempotencyGuard instance:
 *
 *     import { IdempotencyGuard } from "../idempotency";
 *     const dedup = new IdempotencyGuard();
 *
 *   Do NOT share a single instance across multiple listener files.
 *   Reason: if activity.ts and notifications-bus.ts shared one guard, the first
 *   listener to call isNew(event.id) would mark it seen, causing the second
 *   listener to skip the event - silently losing activity logs or notifications.
 *   Each listener needs independent dedup state.
 *
 * ── Guarantee ─────────────────────────────────────────────────────────────────
 *   Within a single listener file, the guard prevents the same event.id from
 *   being processed twice (e.g. a double-emit bug in a route handler, or future
 *   at-least-once delivery from a message broker).
 *
 * ── Limitations ───────────────────────────────────────────────────────────────
 *   In-memory only - does NOT survive server restarts.
 *   TODO(future): Persist processed event IDs in an `event_bus_id` column on
 *     activity_logs / notifications for cross-restart deduplication.
 */

/**
 * IdempotencyGuard - in-process deduplication keyed on an arbitrary string key.
 *
 * Intended usage: key = event.id (UUID v4 generated by the EventBus per emit).
 *
 * @param ttlMs  How long to remember a processed key before expiry.
 *               Default: 5 minutes.  Expired keys are eligible for re-processing.
 *               During a typical request lifecycle this window is more than
 *               sufficient; the main protection target is the same-process
 *               double-emit scenario, not cross-request replay.
 */
export class IdempotencyGuard {
  private readonly seen = new Set<string>();
  private readonly ttlMs: number;

  constructor(ttlMs = 5 * 60 * 1000) {
    this.ttlMs = ttlMs;
  }

  /**
   * Returns true  if this key has NOT been seen before → caller should process.
   * Returns false if this key was already processed    → caller should skip (duplicate).
   *
   * Schedules automatic eviction of the key after `ttlMs` to bound memory growth.
   */
  isNew(key: string): boolean {
    if (this.seen.has(key)) return false;
    this.seen.add(key);
    setTimeout(() => this.seen.delete(key), this.ttlMs);
    return true;
  }
}
