import { Router, type IRouter } from "express";
import { requireDatabase } from "../middlewares/requireDatabase";
import setupRouter from "./setup";
import authRouter from "./auth";
import healthRouter from "./health";
import contactRouter from "./contact";
import workspacesRouter from "./workspaces";
import invitationsRouter from "./invitations";
import adminRouter from "./admin";
import platformRouter from "./platform";
import dashboardRouter from "./dashboard";
import departmentsRouter from "./departments";
import usersRouter from "./users";
import groupsRouter from "./groups";
import messagesRouter from "./messages";
import ticketsRouter from "./tickets";
import commentsRouter from "./comments";
import notificationsRouter from "./notifications";
import approvalsRouter from "./approvals";
import activityRouter from "./activity";
import calendarRouter from "./calendar";
import workspaceRolesRouter from "./workspace-roles";
import modulesRouter from "./modules";
import eventsRouter from "./events";
import workflowsRouter from "./workflows";
import governanceRouter from "./governance";
import formsRouter from "./forms";
import dataSourcesRouter from "./datasources";
import hrRouter from "./hr";
import mePayslipsRouter from "./me-payslips";
import platformRuntimeRouter from "./platform-runtime";
import hrImportV2Router from "./hr-import-v2";
import hrImportRuntimeRouter from "./hr-import-runtime";
import hrImportStagingRouter from "./hr-import-staging";
import hrFoundationImportRouter from "./hr-foundation-import";
import hrFoundationMergeRouter from "./hr-foundation-merge";
import hrEmployeeAccountRouter from "./hr-employee-account";
import hrLeaveMigrationRouter from "./hr-leave-migration";
import hrEmployeeProvisionRouter from "./hr-employee-provision";
import hrPayrollMigrationRouter from "./hr-payroll-migration";
import workforceAttendanceRouter from "./workforce-attendance";
import workforceAttendanceImportRouter from "./workforce-attendance-import";
import attendanceIntegrationsRouter from "./attendance-integrations";
import workforceOperationsRouter from "./workforce-operations";
import workforceHealthRouter from "./workforce-health";
import payrollCanonicalRouter from "./payroll-canonical";
import payrollOperationsRouter from "./payroll-operations";
import leaveRouter from "./leave";
import approvalInboxRouter from "./approval-inbox";
import workspaceSmtpRouter from "./workspace-smtp";
import attachmentsRouter from "./attachments";
import reportsRouter from "./reports";
import storageRouter from "./storage";
import streamRouter from "./stream";
import platformSettingsRouter from "./platform-settings";
import tenantsRouter from "./tenants";
import platformUserConsoleRouter from "./platform-user-console";
import platformUsersRouter from "./platform-users";
import platformUserPermissionsRouter from "./platform-user-permissions";
import platformAdminProtectionRouter from "./platform-admin-protection";
import platformAccessReviewRouter from "./platform-access-review";
import platformUserInvitationsRouter from "./platform-user-invitations";
import platformMeRouter from "./platform-me";
import platformActivityRouter from "./platform-activity";
import commercialRouter from "./commercial";
import commercialContractsRouter from "./commercial-contracts";
import commercialInvoicesRouter from "./commercial-invoices";
import tenantBillingRouter from "./tenant-billing";
import commercialRiskRouter from "./commercial-risk";
import commercialActivityRouter from "./commercial-activity";
import workspaceSubscriptionsRouter from "./workspace-subscriptions";
import workspaceAccessRouter from "./workspace-access";
import tenantWorkspaceAccessRouter from "./tenant-workspace-access";
import tenantProductModulesRouter from "./tenant-product-modules";
import platformGovernanceRouter from "./platform-governance";
import workspaceStabilizationRouter from "./workspace-stabilization";
import { workspaceAccessWriteGuard } from "../middlewares/workspaceAccessWriteGuard";

const router: IRouter = Router();

// ── Public routes (no database required) ─────────────────────────────────────
router.use(setupRouter);
router.use(authRouter);
router.use(healthRouter);
router.use(contactRouter);

// ── Database guard - returns 503 for all routes below when DATABASE_URL unset ─
router.use(requireDatabase);

// P16-E: block operational writes when workspace is in read-only mode
router.use(workspaceAccessWriteGuard);

// ── DB-dependent routes ───────────────────────────────────────────────────────
router.use(workspacesRouter);
router.use(invitationsRouter);
router.use(adminRouter);
router.use(platformActivityRouter);
router.use(platformRouter);
router.use(dashboardRouter);
router.use(departmentsRouter);
router.use(usersRouter);
router.use(groupsRouter);
router.use(messagesRouter);
router.use(ticketsRouter);
router.use(commentsRouter);
router.use(notificationsRouter);
router.use(approvalsRouter);
router.use(activityRouter);
router.use(calendarRouter);
router.use(workspaceRolesRouter);
router.use(modulesRouter);
router.use(workspaceStabilizationRouter);
router.use(eventsRouter);
router.use(workflowsRouter);
router.use(governanceRouter);
router.use(dataSourcesRouter);
router.use(formsRouter);
router.use(mePayslipsRouter);
router.use(hrRouter);
router.use(hrFoundationImportRouter);
router.use(hrFoundationMergeRouter);
router.use(hrImportStagingRouter);
router.use(hrImportRuntimeRouter);
router.use(hrImportV2Router);
router.use(platformRuntimeRouter);
router.use(hrEmployeeAccountRouter);
router.use(hrLeaveMigrationRouter);
router.use(hrEmployeeProvisionRouter);
router.use(hrPayrollMigrationRouter);
router.use(workforceAttendanceRouter);
router.use(workforceAttendanceImportRouter);
router.use(attendanceIntegrationsRouter);
router.use(workforceOperationsRouter);
router.use(payrollCanonicalRouter);
router.use(payrollOperationsRouter);
router.use(leaveRouter);
router.use(approvalInboxRouter);
router.use(workforceHealthRouter);
router.use(workspaceSmtpRouter);
router.use(attachmentsRouter);
router.use(reportsRouter);
router.use(storageRouter);
router.use(streamRouter);
router.use(platformSettingsRouter);
router.use(tenantsRouter);
router.use(platformGovernanceRouter);
router.use(platformUserConsoleRouter);
router.use(platformUsersRouter);
router.use(platformUserPermissionsRouter);
router.use(platformAdminProtectionRouter);
router.use(platformAccessReviewRouter);
router.use(platformUserInvitationsRouter);
router.use(platformMeRouter);
router.use(commercialRouter);
router.use(commercialContractsRouter);
router.use(commercialInvoicesRouter);
router.use(tenantBillingRouter);
router.use(commercialRiskRouter);
router.use(commercialActivityRouter);
router.use(workspaceSubscriptionsRouter);
router.use(tenantProductModulesRouter);
router.use(workspaceAccessRouter);
router.use(tenantWorkspaceAccessRouter);

export default router;
