import { db } from "@workspace/db";
import { platformModulesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const INITIAL_MODULES = [
  {
    key: "home",
    name: "Home",
    nameAr: "الرئيسية",
    description: "Personal workspace home with quick actions",
    descriptionAr: "الصفحة الرئيسية مع الإجراءات السريعة",
    icon: "Home",
    category: "core",
    core: true,
    defaultEnabled: true,
    navigationPath: "/home",
    permissionKey: null,
    displayOrder: 0,
  },
  {
    key: "dashboard",
    name: "Dashboard",
    nameAr: "لوحة التحكم",
    description: "Overview of workspace activity and statistics",
    descriptionAr: "نظرة عامة على نشاط مساحة العمل والإحصائيات",
    icon: "LayoutDashboard",
    category: "core",
    core: false,
    defaultEnabled: true,
    navigationPath: "/dashboard",
    permissionKey: "dashboard.view",
    displayOrder: 1,
  },
  {
    key: "messages",
    name: "Messages",
    nameAr: "الرسائل",
    description: "Internal messaging and team communication",
    descriptionAr: "المراسلة الداخلية وتواصل الفريق",
    icon: "Mail",
    category: "communication",
    core: false,
    defaultEnabled: true,
    navigationPath: "/messages",
    permissionKey: "messages.view",
    displayOrder: 2,
  },
  {
    key: "calendar",
    name: "Calendar",
    nameAr: "التقويم",
    description: "Team calendar, events and scheduling",
    descriptionAr: "تقويم الفريق والأحداث والجدولة",
    icon: "CalendarDays",
    category: "productivity",
    core: false,
    defaultEnabled: true,
    navigationPath: "/calendar",
    permissionKey: "calendar.view",
    displayOrder: 3,
  },
  {
    key: "tickets",
    name: "Tickets",
    nameAr: "التذاكر",
    description: "Issue tracking, requests and task management",
    descriptionAr: "تتبع المشكلات والطلبات وإدارة المهام",
    icon: "Ticket",
    category: "operations",
    core: false,
    defaultEnabled: true,
    navigationPath: "/tickets",
    permissionKey: "tickets.view",
    displayOrder: 4,
  },
  {
    key: "approvals",
    name: "Approvals",
    nameAr: "الموافقات",
    description: "Approval workflows and authorization queue",
    descriptionAr: "سير عمل الموافقات وقائمة التفويض",
    icon: "CheckSquare",
    category: "operations",
    core: false,
    defaultEnabled: true,
    navigationPath: null,
    permissionKey: "approvals.view",
    displayOrder: 5,
  },
  {
    key: "departments",
    name: "Departments",
    nameAr: "الأقسام",
    description: "Organizational structure and department management",
    descriptionAr: "الهيكل التنظيمي وإدارة الأقسام",
    icon: "Building2",
    category: "organization",
    core: false,
    defaultEnabled: true,
    navigationPath: "/departments",
    permissionKey: "departments.view",
    displayOrder: 6,
  },
  {
    key: "groups",
    name: "Groups",
    nameAr: "المجموعات",
    description: "Team groups and cross-department collaboration",
    descriptionAr: "مجموعات الفريق والتعاون بين الأقسام",
    icon: "UsersRound",
    category: "organization",
    core: false,
    defaultEnabled: true,
    navigationPath: "/groups",
    permissionKey: "groups.view",
    displayOrder: 7,
  },
  {
    key: "users",
    name: "Users",
    nameAr: "المستخدمون",
    description: "Employee directory and user management",
    descriptionAr: "دليل الموظفين وإدارة المستخدمين",
    icon: "Users",
    category: "organization",
    core: false,
    defaultEnabled: true,
    navigationPath: "/users",
    permissionKey: "users.view",
    displayOrder: 8,
  },
  {
    key: "notifications",
    name: "Notifications",
    nameAr: "الإشعارات",
    description: "System notifications and alerts center",
    descriptionAr: "مركز الإشعارات والتنبيهات",
    icon: "Bell",
    category: "core",
    core: true,
    defaultEnabled: true,
    navigationPath: "/notifications",
    permissionKey: "notifications.view",
    displayOrder: 9,
  },
  {
    key: "roles",
    name: "Roles & Permissions",
    nameAr: "الأدوار والصلاحيات",
    description: "Custom roles and permission management",
    descriptionAr: "إدارة الأدوار والصلاحيات المخصصة",
    icon: "ShieldCheck",
    category: "administration",
    core: false,
    defaultEnabled: true,
    navigationPath: "/roles",
    permissionKey: "roles.view",
    displayOrder: 10,
  },
  {
    key: "workflows",
    name: "Workflows",
    nameAr: "سير العمل",
    description: "Event-driven automation workflows",
    descriptionAr: "سير عمل أتمتة مدفوعة بالأحداث",
    icon: "GitFork",
    category: "administration",
    core: false,
    defaultEnabled: true,
    navigationPath: "/workflows",
    permissionKey: "workflow.view",
    displayOrder: 11,
  },
  {
    key: "forms",
    name: "Forms",
    nameAr: "النماذج",
    description: "Dynamic form builder - create, submit, and review multi-field forms",
    descriptionAr: "منشئ نماذج ديناميكي - إنشاء وتقديم ومراجعة النماذج",
    icon: "ClipboardList",
    category: "productivity",
    core: false,
    defaultEnabled: true,
    navigationPath: null,
    permissionKey: "forms.view",
    displayOrder: 12,
  },
  {
    key: "hr",
    name: "Human Resources",
    nameAr: "الموارد البشرية",
    description: "Integrated HCM hub — employees, org structure, and workforce lifecycle",
    descriptionAr: "مركز الموارد البشرية المتكامل — الموظفون والهيكل ودورة الحياة",
    icon: "BriefcaseBusiness",
    category: "hcm",
    core: false,
    defaultEnabled: true,
    navigationPath: "/hr",
    permissionKey: "hr.manage",
    displayOrder: 13,
  },
  {
    key: "payroll",
    name: "Payroll",
    nameAr: "الرواتب",
    description: "Payroll runs, payslips, and compensation export (payroll-scoped finance only)",
    descriptionAr: "دورات الرواتب والقسائم والتصدير — المالية المرتبطة بالرواتب فقط",
    icon: "DollarSign",
    category: "hcm",
    core: false,
    defaultEnabled: true,
    navigationPath: "/admin/hr/payroll",
    permissionKey: "hr.payroll.admin",
    displayOrder: 14,
  },
  {
    key: "attendance",
    name: "Time & Attendance",
    nameAr: "الحضور والانصراف",
    description: "Attendance tracking, import, leave coordination, and workforce time ops",
    descriptionAr: "تتبع الحضور والاستيراد والإجازات وعمليات الوقت",
    icon: "Clock",
    category: "hcm",
    core: false,
    defaultEnabled: true,
    navigationPath: "/admin/hr/attendance",
    permissionKey: "hr.manage",
    displayOrder: 15,
  },
  {
    key: "report-center",
    name: "Report Center",
    nameAr: "مركز التقارير",
    description: "Generated reports, exports, schedules, and workspace documents",
    descriptionAr: "التقارير المُنشأة والتصدير والجداول والمستندات",
    icon: "FileText",
    category: "hcm",
    core: false,
    defaultEnabled: true,
    navigationPath: "/hr/reports",
    permissionKey: "hr.manage",
    displayOrder: 16,
  },
  {
    key: "self-service",
    name: "Employee Self-Service",
    nameAr: "الخدمات الذاتية",
    description: "ESS — leave, attendance, payslips, and HR requests in one portal",
    descriptionAr: "بوابة الموظف — إجازات، حضور، قسائم، وطلبات HR",
    icon: "ConciergeBell",
    category: "hcm",
    core: false,
    defaultEnabled: true,
    navigationPath: "/self-service",
    permissionKey: "self_service.view",
    displayOrder: 17,
  },
  {
    key: "subscription",
    name: "Subscription Status",
    nameAr: "حالة الاشتراك",
    description: "Read-only subscription status, modules, and usage limits",
    descriptionAr: "عرض حالة الاشتراك والموديولات وحدود الاستخدام للقراءة فقط",
    icon: "CreditCard",
    category: "operations",
    core: false,
    defaultEnabled: true,
    navigationPath: "/subscription/status",
    permissionKey: "tenant.subscription.read",
    displayOrder: 17,
  },
];

export async function seedModules() {
  for (const module of INITIAL_MODULES) {
    await db
      .insert(platformModulesTable)
      .values(module)
      .onConflictDoUpdate({
        target: platformModulesTable.key,
        set: {
          name: sql`excluded.name`,
          nameAr: sql`excluded.name_ar`,
          description: sql`excluded.description`,
          descriptionAr: sql`excluded.description_ar`,
          icon: sql`excluded.icon`,
          category: sql`excluded.category`,
          core: sql`excluded.core`,
          defaultEnabled: sql`excluded.default_enabled`,
          navigationPath: sql`excluded.navigation_path`,
          permissionKey: sql`excluded.permission_key`,
          displayOrder: sql`excluded.display_order`,
        },
      });
  }
}
